"""Schema additivo e bootstrap per installazioni nuove o importate."""
import sqlite3
from pathlib import Path


SCHEMA_VERSION = 26
PRIVACY_NOTICE_VERSION = "2026-07-16"
PRIVACY_HISTORY_CUTOFF = "2026-07-16 00:00:00"


DDL = r"""
CREATE TABLE IF NOT EXISTS GYMFLOW_SCHEMA_VERSION(
    VERSION INTEGER PRIMARY KEY, APPLIED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SOCI(
    ID INTEGER PRIMARY KEY, COD_SOC TEXT, RAG_SOC TEXT NOT NULL DEFAULT '', SESSO TEXT,
    DATA_NA TEXT, LU_NA TEXT, COGNOME TEXT, NOME TEXT, INDIR TEXT, CITTA TEXT, CAP TEXT, PROV TEXT, REGIONE TEXT,
    COD_FIS TEXT, PIVA TEXT, TEL TEXT, TEL_PRIV TEXT, EMAIL TEXT, STATO INTEGER DEFAULT 2,
    NOTE1 TEXT, MEDICO TEXT, DT_IN_CM TEXT, DT_SC_CM TEXT, DATA_IS TEXT, PROFES TEXT,
    BIO TEXT, FEDERATION_NAME TEXT, FEDERATION_CARD TEXT, FEDERATION_EXPIRY TEXT,
    GUARDIAN_NAME TEXT, GUARDIAN_TAX_CODE TEXT, GUARDIAN_RELATIONSHIP TEXT,
    GUARDIAN_EMAIL TEXT, GUARDIAN_PHONE TEXT,
    DATA_NEW TEXT, DATA_AGG TEXT
);
CREATE INDEX IF NOT EXISTS IX_SOCI_NOME ON SOCI(RAG_SOC);
CREATE INDEX IF NOT EXISTS IX_SOCI_CODICE ON SOCI(COD_SOC);

CREATE TABLE IF NOT EXISTS LISTINI(
    ID INTEGER PRIMARY KEY, DESCR TEXT NOT NULL, GIORNI INTEGER DEFAULT 0,
    DURATA INTEGER DEFAULT 0, PREZZO REAL DEFAULT 0, ACTIVITY_ID INTEGER,
    FREQUENCY_LABEL TEXT, PRICING_MODE TEXT NOT NULL DEFAULT 'FIXED',
    ACTIVE INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS GYMFLOW_PRICE_TIERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, PRICE_LIST_ID INTEGER NOT NULL,
    MIN_LESSONS INTEGER NOT NULL, MAX_LESSONS INTEGER,
    UNIT_PRICE REAL NOT NULL, ACTIVE INTEGER NOT NULL DEFAULT 1,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(PRICE_LIST_ID,MIN_LESSONS),
    FOREIGN KEY(PRICE_LIST_ID) REFERENCES LISTINI(ID)
);
CREATE INDEX IF NOT EXISTS IX_PRICE_TIERS_LIST
    ON GYMFLOW_PRICE_TIERS(PRICE_LIST_ID,ACTIVE,MIN_LESSONS);
CREATE TABLE IF NOT EXISTS ATTIVITA(
    ID INTEGER PRIMARY KEY, DESCR TEXT NOT NULL, COSTO_UN REAL DEFAULT 0, IVA REAL DEFAULT 0,
    ACTIVE INTEGER NOT NULL DEFAULT 1, PALESYA_KIND TEXT,
    PALESYA_SECTOR TEXT, PALESYA_SUBSECTOR TEXT,
    PALESYA_TAXONOMY_SOURCE TEXT,
    PALESYA_TAXONOMY_CONFIDENCE INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS ISTRU(
    ID INTEGER PRIMARY KEY, NOMIN TEXT NOT NULL, EMAIL TEXT, TEL TEXT,
    ACTIVE INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS MODPAG(
    ID INTEGER PRIMARY KEY, DESCRIZIONE TEXT NOT NULL, ACTIVE INTEGER NOT NULL DEFAULT 1
);
INSERT OR IGNORE INTO MODPAG(ID, DESCRIZIONE) VALUES
    (0, 'Contanti'), (1, 'Carta'), (2, 'Bonifico');

CREATE TABLE IF NOT EXISTS TESSERE(
    ID INTEGER PRIMARY KEY, STATO TEXT, COD_SOC INTEGER NOT NULL, COD_LIS INTEGER,
    COD_ATT INTEGER, DATA_VAL TEXT, DATA_FIN TEXT, DATA_REG TEXT, IMPORTO REAL DEFAULT 0,
    IMP_TOT REAL DEFAULT 0, ISTRUT INTEGER, NUM_MAX INTEGER DEFAULT 0,
    MAX_WEEKLY_ENTRIES INTEGER DEFAULT 0, MAX_MONTHLY_ENTRIES INTEGER DEFAULT 0,
    OMAGGIO INTEGER DEFAULT 0,
    SCONTO_PCT REAL DEFAULT 0, LESSON_COUNT INTEGER, UNIT_PRICE REAL,
    DATA_NEW TEXT, DATA_AGG TEXT, COD_CEN INTEGER DEFAULT 1
);
CREATE INDEX IF NOT EXISTS IX_TESSERE_SOCIO ON TESSERE(COD_SOC);

CREATE TABLE IF NOT EXISTS CASSA(
    ID INTEGER PRIMARY KEY, DATA TEXT, COD_SOCIO INTEGER, DESCR TEXT, IMPORTO REAL DEFAULT 0,
    IMPONIB REAL DEFAULT 0, MOD_PAG INTEGER DEFAULT 0, T_OP TEXT DEFAULT 'E', COD_ATT INTEGER,
    TITOLO INTEGER, COD_CEN INTEGER DEFAULT 1, N_INT_FT TEXT, DATA_NEW TEXT, DATA_AGG TEXT
);
CREATE INDEX IF NOT EXISTS IX_CASSA_DATA ON CASSA(DATA);

CREATE TABLE IF NOT EXISTS SCADENZ(
    ID INTEGER PRIMARY KEY, COD_SOC INTEGER, DATA TEXT, SCADENZA TEXT, DESCR TEXT,
    IMPORTO REAL DEFAULT 0, VERSATO REAL DEFAULT 0, SALDO REAL DEFAULT 0,
    ID_TESSERA INTEGER
);
CREATE TABLE IF NOT EXISTS RINGRES(
    ID INTEGER PRIMARY KEY, DATA_AGG TEXT, DATA_NEW TEXT, COD_UT_C INTEGER, COD_UT INTEGER,
    TIP_MOD TEXT, COD_SOC INTEGER, DATA_IN TEXT, ORA_IN TEXT, ORA_USC TEXT, TIPO TEXT,
    SERV INTEGER, TERMIN INTEGER, MIN_ADD INTEGER, COD_CEN INTEGER, ID_TESSERA INTEGER, NOTE TEXT
);
CREATE INDEX IF NOT EXISTS IX_RINGRES_SOCIO_DATA ON RINGRES(COD_SOC, DATA_IN);

CREATE TABLE IF NOT EXISTS GYMFLOW_USERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, USERNAME TEXT NOT NULL UNIQUE, PASSWORD_HASH TEXT NOT NULL,
    ROLE TEXT NOT NULL DEFAULT 'reception', SOCIO_ID INTEGER, ACTIVE INTEGER NOT NULL DEFAULT 1,
    DISPLAY_NAME TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, LAST_LOGIN_AT TEXT,
    TOTP_SECRET TEXT, TOTP_ENABLED INTEGER NOT NULL DEFAULT 0,
    FAILED_LOGIN_COUNT INTEGER NOT NULL DEFAULT 0, LOCKED_UNTIL TEXT
);
CREATE TABLE IF NOT EXISTS GYMFLOW_SESSIONS(
    TOKEN_HASH TEXT PRIMARY KEY, USER_ID INTEGER NOT NULL, CSRF_TOKEN TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL, EXPIRES_AT TEXT NOT NULL, MFA_VERIFIED INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS GYMFLOW_MFA_RECOVERY_CODES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, USER_ID INTEGER NOT NULL, CODE_HASH TEXT NOT NULL UNIQUE,
    USED_AT TEXT, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS GYMFLOW_PASSWORD_RESET_TOKENS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SITE_ID INTEGER NOT NULL,
    INSTALLATION_ID TEXT NOT NULL,
    TOKEN_HASH TEXT NOT NULL UNIQUE,
    REQUESTED_BY TEXT NOT NULL DEFAULT 'ADMIN',
    EXPIRES_AT TEXT NOT NULL,
    USED_AT TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_GYMFLOW_PASSWORD_RESET_INSTALL
    ON GYMFLOW_PASSWORD_RESET_TOKENS(INSTALLATION_ID, USED_AT, EXPIRES_AT);
CREATE TABLE IF NOT EXISTS GYMFLOW_AUDIT(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID INTEGER, ACTION TEXT NOT NULL, ENTITY_TYPE TEXT, ENTITY_ID TEXT, DETAIL TEXT,
    IP_ADDRESS TEXT
);

CREATE TABLE IF NOT EXISTS GYMFLOW_SITES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL, CODE TEXT NOT NULL UNIQUE,
    ACTIVE INTEGER NOT NULL DEFAULT 1
);
INSERT OR IGNORE INTO GYMFLOW_SITES(ID, NAME, CODE) VALUES(1, 'Sede principale', 'MAIN');

CREATE TABLE IF NOT EXISTS GYMFLOW_BUSINESS_PROFILE(
    ID INTEGER PRIMARY KEY CHECK(ID=1), DISPLAY_NAME TEXT, LEGAL_NAME TEXT,
    VAT_NUMBER TEXT, TAX_CODE TEXT, ADDRESS TEXT, CITY TEXT, POSTAL_CODE TEXT,
    PROVINCE TEXT, COUNTRY TEXT NOT NULL DEFAULT 'Italia', EMAIL TEXT, PHONE TEXT,
    PEC TEXT, SDI_CODE TEXT, WEBSITE TEXT, BRAND_COLOR TEXT NOT NULL DEFAULT '#123B34',
    LOGO_PATH TEXT, RECEIPT_FOOTER TEXT,
    FACILITY_TYPE TEXT NOT NULL DEFAULT 'MULTISPORT',
    REGISTRATION_TERMS_GYM TEXT, REGISTRATION_TERMS_POOL TEXT,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT OR IGNORE INTO GYMFLOW_BUSINESS_PROFILE(ID, COUNTRY, BRAND_COLOR)
VALUES(1, 'Italia', '#123B34');

CREATE TABLE IF NOT EXISTS GYMFLOW_RECEIPT_COUNTERS(
    YEAR INTEGER PRIMARY KEY, LAST_NUMBER INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS GYMFLOW_RECEIPTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, PAYMENT_ID INTEGER NOT NULL UNIQUE,
    RECEIPT_YEAR INTEGER NOT NULL, RECEIPT_SEQUENCE INTEGER NOT NULL,
    RECEIPT_NUMBER TEXT NOT NULL UNIQUE, ISSUED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SNAPSHOT_JSON TEXT, SNAPSHOT_AT TEXT, STATUS TEXT NOT NULL DEFAULT 'ISSUED',
    VOIDED_AT TEXT, VOID_REASON TEXT, VOIDED_BY INTEGER,
    UNIQUE(RECEIPT_YEAR, RECEIPT_SEQUENCE)
);
CREATE INDEX IF NOT EXISTS IX_GYMFLOW_RECEIPTS_ISSUED
    ON GYMFLOW_RECEIPTS(RECEIPT_YEAR, RECEIPT_SEQUENCE DESC);
CREATE TABLE IF NOT EXISTS GYMFLOW_RECEIPT_ITEMS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PAYMENT_ID INTEGER NOT NULL,
    POSITION INTEGER NOT NULL DEFAULT 1,
    DESCRIPTION TEXT NOT NULL,
    ACTIVITY_ID INTEGER,
    PRICE_LIST_ID INTEGER,
    AMOUNT REAL NOT NULL DEFAULT 0,
    COMPETENCE TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(PAYMENT_ID, POSITION)
);
CREATE INDEX IF NOT EXISTS IX_GYMFLOW_RECEIPT_ITEMS_PAYMENT
    ON GYMFLOW_RECEIPT_ITEMS(PAYMENT_ID, POSITION);

CREATE TABLE IF NOT EXISTS GYMFLOW_CRM_CONTACTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SITE_ID INTEGER NOT NULL DEFAULT 1, SOCIO_ID INTEGER,
    NAME TEXT NOT NULL, EMAIL TEXT, PHONE TEXT, SOURCE TEXT, CAMPAIGN TEXT, OWNER TEXT,
    STATUS TEXT NOT NULL DEFAULT 'NUOVO', VALUE_CENTS INTEGER NOT NULL DEFAULT 0,
    CONSENT_EMAIL INTEGER NOT NULL DEFAULT 0, CONSENT_SMS INTEGER NOT NULL DEFAULT 0,
    NOTES TEXT, NEXT_FOLLOWUP TEXT, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_CRM_STATUS ON GYMFLOW_CRM_CONTACTS(STATUS, NEXT_FOLLOWUP);
CREATE TABLE IF NOT EXISTS GYMFLOW_CRM_ACTIVITIES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, CONTACT_ID INTEGER NOT NULL, KIND TEXT NOT NULL,
    NOTE TEXT, DUE_AT TEXT, COMPLETED_AT TEXT, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GYMFLOW_CLASSES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SITE_ID INTEGER NOT NULL DEFAULT 1, NAME TEXT NOT NULL,
    ACTIVITY_ID INTEGER, INSTRUCTOR_ID INTEGER, ROOM TEXT, START_AT TEXT NOT NULL,
    END_AT TEXT NOT NULL, CAPACITY INTEGER NOT NULL DEFAULT 1, STATUS TEXT NOT NULL DEFAULT 'OPEN',
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_CLASSES_START ON GYMFLOW_CLASSES(START_AT);
CREATE TABLE IF NOT EXISTS GYMFLOW_BOOKINGS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, CLASS_ID INTEGER NOT NULL, SOCIO_ID INTEGER NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'BOOKED', POSITION INTEGER, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECKED_IN_AT TEXT, UNIQUE(CLASS_ID, SOCIO_ID)
);

CREATE TABLE IF NOT EXISTS GYMFLOW_COURSE_TYPES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL, ACTIVITY_ID INTEGER,
    AREA TEXT NOT NULL DEFAULT 'CORSI', DURATION_MINUTES INTEGER NOT NULL DEFAULT 50,
    EARLY_ENTRY_MINUTES INTEGER NOT NULL DEFAULT 10, LATE_ENTRY_MINUTES INTEGER NOT NULL DEFAULT 10,
    COLOR TEXT NOT NULL DEFAULT '#178337', ACTIVE INTEGER NOT NULL DEFAULT 1,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(NAME, AREA)
);
CREATE TABLE IF NOT EXISTS GYMFLOW_SCHEDULE_SLOTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, COURSE_TYPE_ID INTEGER NOT NULL,
    WEEKDAY INTEGER NOT NULL CHECK(WEEKDAY BETWEEN 0 AND 6), START_TIME TEXT NOT NULL,
    END_TIME TEXT NOT NULL, RESOURCE TEXT NOT NULL DEFAULT '', LANE_LABEL TEXT NOT NULL DEFAULT '',
    LANE_COUNT INTEGER NOT NULL DEFAULT 1, CAPACITY_PER_LANE INTEGER NOT NULL DEFAULT 10,
    CAPACITY_LIMIT INTEGER, UNLIMITED_CAPACITY INTEGER NOT NULL DEFAULT 0,
    INSTRUCTOR_ID INTEGER, ACTIVE INTEGER NOT NULL DEFAULT 1, NOTES TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(COURSE_TYPE_ID, WEEKDAY, START_TIME, RESOURCE, LANE_LABEL),
    FOREIGN KEY(COURSE_TYPE_ID) REFERENCES GYMFLOW_COURSE_TYPES(ID)
);
CREATE INDEX IF NOT EXISTS IX_SCHEDULE_SLOTS_DAY_TIME ON GYMFLOW_SCHEDULE_SLOTS(WEEKDAY,START_TIME);
CREATE TABLE IF NOT EXISTS GYMFLOW_SLOT_ENROLLMENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SLOT_ID INTEGER NOT NULL, SOCIO_ID INTEGER NOT NULL,
    SUBSCRIPTION_ID INTEGER, START_DATE TEXT NOT NULL, END_DATE TEXT, STATUS TEXT NOT NULL DEFAULT 'ACTIVE',
    LANE_NUMBER INTEGER, BOOKING_KIND TEXT NOT NULL DEFAULT 'STANDARD',
    PAYMENT_REQUIRED INTEGER NOT NULL DEFAULT 1, NOTE TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(SLOT_ID, SOCIO_ID, START_DATE),
    FOREIGN KEY(SLOT_ID) REFERENCES GYMFLOW_SCHEDULE_SLOTS(ID)
);
CREATE INDEX IF NOT EXISTS IX_SLOT_ENROLLMENTS_SOCIO ON GYMFLOW_SLOT_ENROLLMENTS(SOCIO_ID,STATUS);
CREATE INDEX IF NOT EXISTS IX_SLOT_ENROLLMENTS_SLOT_ACTIVE ON GYMFLOW_SLOT_ENROLLMENTS(SLOT_ID,STATUS,START_DATE,END_DATE);

CREATE TABLE IF NOT EXISTS GYMFLOW_PLANNING_HISTORY(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SOURCE_SYSTEM TEXT NOT NULL DEFAULT 'LEGACY',
    SOURCE_TABLE TEXT NOT NULL, SOURCE_ID TEXT NOT NULL, SLOT_ID INTEGER,
    SOCIO_ID INTEGER NOT NULL, BOOKING_DATE TEXT NOT NULL, COURSE_NAME TEXT NOT NULL,
    AREA TEXT NOT NULL DEFAULT 'CORSI', RESOURCE TEXT NOT NULL DEFAULT '',
    START_TIME TEXT NOT NULL, STATUS TEXT NOT NULL DEFAULT 'BOOKED',
    IMPORTED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(SOURCE_SYSTEM,SOURCE_TABLE,SOURCE_ID),
    FOREIGN KEY(SLOT_ID) REFERENCES GYMFLOW_SCHEDULE_SLOTS(ID)
);
CREATE INDEX IF NOT EXISTS IX_PLANNING_HISTORY_DATE ON GYMFLOW_PLANNING_HISTORY(BOOKING_DATE);
CREATE INDEX IF NOT EXISTS IX_PLANNING_HISTORY_SOCIO ON GYMFLOW_PLANNING_HISTORY(SOCIO_ID,BOOKING_DATE);
CREATE INDEX IF NOT EXISTS IX_PLANNING_HISTORY_SLOT ON GYMFLOW_PLANNING_HISTORY(SLOT_ID,BOOKING_DATE);

CREATE TABLE IF NOT EXISTS GYMFLOW_EXERCISES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL UNIQUE, MUSCLE_GROUP TEXT,
    DESCRIPTION TEXT, ACTIVE INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS GYMFLOW_WORKOUTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SOCIO_ID INTEGER, NAME TEXT NOT NULL,
    INSTRUCTOR_ID INTEGER, IS_TEMPLATE INTEGER NOT NULL DEFAULT 0, START_DATE TEXT,
    EXPIRES_AT TEXT, NOTES TEXT, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS GYMFLOW_WORKOUT_ITEMS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, WORKOUT_ID INTEGER NOT NULL, EXERCISE_ID INTEGER NOT NULL,
    DAY_NO INTEGER NOT NULL DEFAULT 1, SORT_ORDER INTEGER NOT NULL DEFAULT 0, SETS INTEGER,
    REPS TEXT, LOAD_TEXT TEXT, REST_SECONDS INTEGER, NOTES TEXT
);
CREATE TABLE IF NOT EXISTS GYMFLOW_MEASUREMENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SOCIO_ID INTEGER NOT NULL, MEASURED_AT TEXT NOT NULL,
    WEIGHT_KG REAL, HEIGHT_CM REAL, BODY_FAT_PCT REAL, MUSCLE_PCT REAL, WAIST_CM REAL,
    CHEST_CM REAL, NOTES TEXT
);

CREATE TABLE IF NOT EXISTS GYMFLOW_PRODUCTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SITE_ID INTEGER NOT NULL DEFAULT 1, SKU TEXT UNIQUE,
    BARCODE TEXT UNIQUE, NAME TEXT NOT NULL, CATEGORY TEXT, PRICE_CENTS INTEGER NOT NULL DEFAULT 0,
    COST_CENTS INTEGER NOT NULL DEFAULT 0, STOCK_QTY REAL NOT NULL DEFAULT 0,
    MIN_STOCK_QTY REAL NOT NULL DEFAULT 0, ACTIVE INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS GYMFLOW_STOCK_MOVEMENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, PRODUCT_ID INTEGER NOT NULL, QUANTITY REAL NOT NULL,
    REASON TEXT NOT NULL, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, USER_ID INTEGER
);
CREATE TABLE IF NOT EXISTS GYMFLOW_WALLET_MOVEMENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SOCIO_ID INTEGER NOT NULL, AMOUNT_CENTS INTEGER NOT NULL,
    REASON TEXT NOT NULL, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, USER_ID INTEGER
);
CREATE TABLE IF NOT EXISTS GYMFLOW_SALES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SITE_ID INTEGER NOT NULL DEFAULT 1, SOCIO_ID INTEGER,
    TOTAL_CENTS INTEGER NOT NULL, PAYMENT_METHOD TEXT NOT NULL, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS GYMFLOW_SALE_ITEMS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SALE_ID INTEGER NOT NULL, PRODUCT_ID INTEGER NOT NULL,
    QUANTITY REAL NOT NULL, UNIT_PRICE_CENTS INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS GYMFLOW_QR_NONCES(
    NONCE TEXT PRIMARY KEY, SOCIO_ID INTEGER NOT NULL, EXPIRES_AT TEXT NOT NULL, USED_AT TEXT
);
CREATE TABLE IF NOT EXISTS GYMFLOW_NOTIFICATIONS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SOCIO_ID INTEGER, CONTACT_ID INTEGER, CHANNEL TEXT NOT NULL,
    TEMPLATE_KEY TEXT, SUBJECT TEXT, BODY TEXT NOT NULL, STATUS TEXT NOT NULL DEFAULT 'PENDING',
    SCHEDULED_AT TEXT, SENT_AT TEXT, ERROR TEXT
);
CREATE TABLE IF NOT EXISTS GYMFLOW_COMMUNICATIONS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CHANNEL TEXT NOT NULL,
    SUBJECT TEXT,
    BODY TEXT NOT NULL,
    AUDIENCE_JSON TEXT,
    RECIPIENT_COUNT INTEGER NOT NULL DEFAULT 0,
    STATUS TEXT NOT NULL DEFAULT 'PREPARED',
    CREATED_BY INTEGER,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_GYMFLOW_COMMUNICATIONS_CREATED
    ON GYMFLOW_COMMUNICATIONS(CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS GYMFLOW_ORGANIZATIONS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL, VAT_NUMBER TEXT, EMAIL TEXT,
    PHONE TEXT, BILLING_OWNER TEXT NOT NULL DEFAULT 'CIRO',
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS GYMFLOW_FLEET_SITES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, ORGANIZATION_ID INTEGER NOT NULL, NAME TEXT NOT NULL,
    CODE TEXT NOT NULL, ADDRESS TEXT, CONTACT_NAME TEXT, CONTACT_EMAIL TEXT, CONTACT_PHONE TEXT,
    BILLING_OWNER TEXT NOT NULL DEFAULT 'CIRO',
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(ORGANIZATION_ID) REFERENCES GYMFLOW_ORGANIZATIONS(ID),
    UNIQUE(ORGANIZATION_ID,CODE)
);
CREATE TABLE IF NOT EXISTS GYMFLOW_CONFIGURATION_PROFILES(
    ID TEXT PRIMARY KEY, NAME TEXT NOT NULL, SITE_ID INTEGER, VERSION INTEGER NOT NULL DEFAULT 1,
    PAYLOAD TEXT NOT NULL, PAYLOAD_SHA256 TEXT NOT NULL, ACTIVE INTEGER NOT NULL DEFAULT 1,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(SITE_ID) REFERENCES GYMFLOW_FLEET_SITES(ID)
);
CREATE TABLE IF NOT EXISTS GYMFLOW_APPLIED_CONFIG_PROFILES(
    PROFILE_ID TEXT PRIMARY KEY, VERSION INTEGER NOT NULL, PAYLOAD_SHA256 TEXT NOT NULL,
    APPLIED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS GYMFLOW_LICENSES(
    ID TEXT PRIMARY KEY, SITE_ID INTEGER NOT NULL UNIQUE, PLAN_CODE TEXT NOT NULL DEFAULT 'PILOT',
    STATUS TEXT NOT NULL DEFAULT 'PENDING', VALID_UNTIL TEXT, GRACE_UNTIL TEXT,
    MONTHLY_PRICE_CENTS INTEGER NOT NULL DEFAULT 0, SETUP_PRICE_CENTS INTEGER NOT NULL DEFAULT 0,
    BILLING_INTERVAL TEXT NOT NULL DEFAULT 'MONTH',
    CURRENCY TEXT NOT NULL DEFAULT 'EUR',
    BILLING_PROVIDER TEXT NOT NULL DEFAULT 'PAYPAL',
    BILLING_OWNER TEXT NOT NULL DEFAULT 'CIRO',
    PROVIDER_CUSTOMER_ID TEXT, PROVIDER_SUBSCRIPTION_ID TEXT, CONFIG_PROFILE_ID TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(SITE_ID) REFERENCES GYMFLOW_FLEET_SITES(ID),
    FOREIGN KEY(CONFIG_PROFILE_ID) REFERENCES GYMFLOW_CONFIGURATION_PROFILES(ID)
);
CREATE INDEX IF NOT EXISTS IX_GYMFLOW_LICENSE_STATUS ON GYMFLOW_LICENSES(STATUS);
CREATE TABLE IF NOT EXISTS GYMFLOW_ACTIVATION_TOKENS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SITE_ID INTEGER NOT NULL, TOKEN_HASH TEXT NOT NULL UNIQUE,
    EXPIRES_AT TEXT NOT NULL, USED_AT TEXT, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(SITE_ID) REFERENCES GYMFLOW_FLEET_SITES(ID)
);
CREATE TABLE IF NOT EXISTS GYMFLOW_INSTALLATIONS(
    ID TEXT PRIMARY KEY, SITE_ID INTEGER NOT NULL, MACHINE_FINGERPRINT TEXT NOT NULL,
    TOKEN_HASH TEXT NOT NULL UNIQUE, RECOVERY_TOKEN_HASH TEXT, APP_VERSION TEXT, OS_NAME TEXT, MIGRATION_STATUS TEXT,
    HARDWARE_STATUS TEXT, BACKUP_STATUS TEXT, LAST_SEEN_AT TEXT, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONFIG_PROFILE_ID TEXT, UPDATE_STATUS TEXT, UPDATE_VERSION TEXT, UPDATE_CHECKED_AT TEXT, UPDATE_ERROR TEXT,
    CONFIG_PROFILE_HASH TEXT, CONFIG_STATUS TEXT, CONFIG_ERROR TEXT,
    DIAGNOSTICS_JSON TEXT, DIAGNOSTICS_AT TEXT, UPDATE_INSTALL_ON_EXIT INTEGER NOT NULL DEFAULT 0,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(SITE_ID, MACHINE_FINGERPRINT),
    FOREIGN KEY(SITE_ID) REFERENCES GYMFLOW_FLEET_SITES(ID),
    FOREIGN KEY(CONFIG_PROFILE_ID) REFERENCES GYMFLOW_CONFIGURATION_PROFILES(ID)
);
CREATE INDEX IF NOT EXISTS IX_GYMFLOW_INSTALLATIONS_SEEN ON GYMFLOW_INSTALLATIONS(LAST_SEEN_AT);
CREATE TABLE IF NOT EXISTS GYMFLOW_REMOTE_COMMANDS(
    ID TEXT PRIMARY KEY, SITE_ID INTEGER NOT NULL, INSTALLATION_ID TEXT NOT NULL,
    COMMAND TEXT NOT NULL, STATUS TEXT NOT NULL DEFAULT 'PENDING',
    REQUESTED_BY TEXT NOT NULL DEFAULT 'ADMIN', RESULT TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, EXPIRES_AT TEXT NOT NULL,
    DELIVERED_AT TEXT, COMPLETED_AT TEXT,
    FOREIGN KEY(SITE_ID) REFERENCES GYMFLOW_FLEET_SITES(ID),
    FOREIGN KEY(INSTALLATION_ID) REFERENCES GYMFLOW_INSTALLATIONS(ID)
);
CREATE INDEX IF NOT EXISTS IX_GYMFLOW_REMOTE_COMMANDS_INSTALL
ON GYMFLOW_REMOTE_COMMANDS(INSTALLATION_ID,STATUS,EXPIRES_AT);
CREATE TABLE IF NOT EXISTS GYMFLOW_FLEET_EVENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, SITE_ID INTEGER, INSTALLATION_ID TEXT, KIND TEXT NOT NULL,
    DETAIL TEXT, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS GYMFLOW_BILLING_EVENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, PROVIDER TEXT NOT NULL, PROVIDER_EVENT_ID TEXT NOT NULL,
    EVENT_TYPE TEXT NOT NULL, CUSTOMER_ID TEXT, SUBSCRIPTION_ID TEXT, SITE_ID INTEGER,
    AMOUNT_CENTS INTEGER NOT NULL DEFAULT 0, CURRENCY TEXT NOT NULL DEFAULT 'EUR', PAYMENT_STATUS TEXT,
    BILLING_OWNER TEXT NOT NULL DEFAULT 'CIRO',
    PROCESSED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(PROVIDER, PROVIDER_EVENT_ID)
);

CREATE TABLE IF NOT EXISTS PALESYA_LEADS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, COMPANY TEXT NOT NULL, CONTACT_NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL, PHONE TEXT NOT NULL, SITES INTEGER NOT NULL DEFAULT 1,
    LEGACY_SOFTWARE TEXT, HARDWARE_NOTES TEXT, SOURCE TEXT NOT NULL DEFAULT 'landing',
    UTM_SOURCE TEXT, UTM_CAMPAIGN TEXT, STATUS TEXT NOT NULL DEFAULT 'NEW',
    PRIVACY_NOTICE_VERSION TEXT, PRIVACY_ACK_AT TEXT,
    MARKETING_CONSENT_AT TEXT,
    CONSENT_AT TEXT NOT NULL, CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_PALESYA_LEADS_STATUS ON PALESYA_LEADS(STATUS, CREATED_AT);

-- Integrazione assistenza telefonica: HubSpot resta il sistema CRM principale;
-- queste tabelle contengono solo stato tecnico, idempotenza e audit minimo.
CREATE TABLE IF NOT EXISTS SUPPORT_WEBHOOK_EVENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SOURCE TEXT NOT NULL,
    EVENT_ID TEXT NOT NULL,
    EVENT_TYPE TEXT,
    CALL_ID TEXT,
    OCCURRED_AT TEXT,
    PAYLOAD_HASH TEXT,
    STATUS TEXT NOT NULL DEFAULT 'RECEIVED',
    ERROR TEXT,
    RECEIVED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROCESSED_AT TEXT,
    UNIQUE(SOURCE, EVENT_ID)
);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_WEBHOOK_CALL ON SUPPORT_WEBHOOK_EVENTS(CALL_ID, RECEIVED_AT);

CREATE TABLE IF NOT EXISTS SUPPORT_CALL_SESSIONS(
    CALL_ID TEXT PRIMARY KEY,
    TELNYX_CALL_ID TEXT,
    VOICE_AI_CALL_ID TEXT,
    FROM_PHONE TEXT,
    TO_PHONE TEXT,
    CUSTOMER_MATCH_STATUS TEXT NOT NULL DEFAULT 'unknown',
    CONTACT_ID TEXT,
    COMPANY_ID TEXT,
    COMPANY_NAME TEXT,
    CONTEXT_JSON TEXT,
    TICKET_ID TEXT,
    STATE TEXT NOT NULL DEFAULT 'started',
    STARTED_AT TEXT,
    ANSWERED_AT TEXT,
    ENDED_AT TEXT,
    DURATION_SECONDS INTEGER,
    SUMMARY_JSON TEXT,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_SESSION_COMPANY ON SUPPORT_CALL_SESSIONS(COMPANY_ID, UPDATED_AT);

CREATE TABLE IF NOT EXISTS SUPPORT_TICKET_LINKS(
    CALL_ID TEXT PRIMARY KEY,
    HUBSPOT_TICKET_ID TEXT NOT NULL UNIQUE,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SUPPORT_CONSUMPTION_LEDGER(
    CALL_ID TEXT PRIMARY KEY,
    EVENT_ID TEXT NOT NULL,
    COMPANY_ID TEXT NOT NULL,
    HUBSPOT_TICKET_ID TEXT,
    BEFORE_COUNT INTEGER NOT NULL,
    AFTER_COUNT INTEGER NOT NULL,
    CONSUMED INTEGER NOT NULL DEFAULT 1,
    STATUS TEXT NOT NULL DEFAULT 'APPLIED',
    REASON TEXT,
    REVERSED_AT TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_LEDGER_COMPANY ON SUPPORT_CONSUMPTION_LEDGER(COMPANY_ID, CREATED_AT);

CREATE TABLE IF NOT EXISTS SUPPORT_AUDIT_LOG(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EVENT_KEY TEXT NOT NULL UNIQUE,
    CALL_ID TEXT,
    COMPANY_ID TEXT,
    HUBSPOT_TICKET_ID TEXT,
    BEFORE_COUNT INTEGER,
    CONSUMED INTEGER NOT NULL DEFAULT 0,
    AFTER_COUNT INTEGER,
    REASON TEXT,
    SOURCE TEXT,
    TELNYX_CALL_ID TEXT,
    VOICE_AI_CALL_ID TEXT,
    ACTOR TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_AUDIT_COMPANY ON SUPPORT_AUDIT_LOG(COMPANY_ID, CREATED_AT);

-- Richieste di ricontatto quando l'escalation umana non va a buon fine (fallback).
CREATE TABLE IF NOT EXISTS SUPPORT_CALLBACKS(
    CALL_ID TEXT PRIMARY KEY,
    COMPANY_ID TEXT,
    CONTACT_ID TEXT,
    CALLER_PHONE TEXT,
    CALLER_NAME TEXT,
    COMPANY_NAME TEXT,
    REASON TEXT,
    CATEGORY TEXT,
    HUBSPOT_TASK_ID TEXT,
    STATUS TEXT NOT NULL DEFAULT 'OPEN',
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_CALLBACK_COMPANY ON SUPPORT_CALLBACKS(COMPANY_ID, CREATED_AT);

-- Idempotenza del log chiamata verso l'oggetto Call nativo di HubSpot.
CREATE TABLE IF NOT EXISTS SUPPORT_CALL_LOG(
    CALL_ID TEXT PRIMARY KEY,
    HUBSPOT_CALL_ID TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Idempotenza delle richieste commerciali (Deal) generate da Mariarosia.
CREATE TABLE IF NOT EXISTS SUPPORT_COMMERCIAL_LINKS(
    CALL_ID TEXT PRIMARY KEY,
    HUBSPOT_DEAL_ID TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""


def _table_columns(connection, table):
    """Restituisce {NOME_MAIUSCOLO: nome_reale} senza assumere lo schema ForFit."""
    return {
        str(row[1]).upper(): str(row[1])
        for row in connection.execute('PRAGMA table_info("{}")'.format(table))
    }


def _quote_sqlite_identifier(value):
    return '"{}"'.format(str(value).replace('"', '""'))


def _rebuild_receipts_without_legacy_cash_foreign_key(connection):
    """Rimuove il FK incompatibile con gli estratti ForFit senza perdere righe.

    In numerosi database legacy ``CASSA.ID`` contiene identificativi validi ma
    non e dichiarato PRIMARY KEY/UNIQUE. SQLite rifiuta quindi ogni INSERT nella
    tabella ricevute se questa dichiara un FK verso quel campo. Il collegamento
    applicativo resta garantito da PAYMENT_ID UNIQUE e dalle JOIN esistenti.
    """
    foreign_keys = list(connection.execute(
        'PRAGMA foreign_key_list("GYMFLOW_RECEIPTS")'
    ))
    if not any(str(row[2]).upper() == "CASSA" for row in foreign_keys):
        return False

    old_table = "GYMFLOW_RECEIPTS_CASSA_FK_OLD"
    connection.execute('DROP TABLE IF EXISTS "{}"'.format(old_table))
    connection.execute(
        'ALTER TABLE "GYMFLOW_RECEIPTS" RENAME TO "{}"'.format(old_table)
    )
    connection.execute("""CREATE TABLE GYMFLOW_RECEIPTS(
        ID INTEGER PRIMARY KEY AUTOINCREMENT, PAYMENT_ID INTEGER NOT NULL UNIQUE,
        RECEIPT_YEAR INTEGER NOT NULL, RECEIPT_SEQUENCE INTEGER NOT NULL,
        RECEIPT_NUMBER TEXT NOT NULL UNIQUE, ISSUED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        SNAPSHOT_JSON TEXT, SNAPSHOT_AT TEXT, STATUS TEXT NOT NULL DEFAULT 'ISSUED',
        VOIDED_AT TEXT, VOID_REASON TEXT, VOIDED_BY INTEGER,
        UNIQUE(RECEIPT_YEAR, RECEIPT_SEQUENCE)
    )""")
    old_columns = _table_columns(connection, old_table)
    target_columns = (
        "ID", "PAYMENT_ID", "RECEIPT_YEAR", "RECEIPT_SEQUENCE",
        "RECEIPT_NUMBER", "ISSUED_AT", "SNAPSHOT_JSON", "SNAPSHOT_AT",
        "STATUS", "VOIDED_AT", "VOID_REASON", "VOIDED_BY",
    )
    common = [column for column in target_columns if column in old_columns]
    if common:
        quoted = ",".join(_quote_sqlite_identifier(column) for column in common)
        connection.execute(
            'INSERT INTO "GYMFLOW_RECEIPTS"({0}) SELECT {0} FROM "{1}"'.format(
                quoted, old_table
            )
        )
    connection.execute('DROP TABLE "{}"'.format(old_table))
    connection.execute("""CREATE INDEX IF NOT EXISTS IX_GYMFLOW_RECEIPTS_ISSUED
        ON GYMFLOW_RECEIPTS(RECEIPT_YEAR, RECEIPT_SEQUENCE DESC)""")
    return True


def _rebuild_leads_with_nullable_privacy_version(connection):
    """Rimuove il vecchio NOT NULL/default SQLite preservando righe e indici."""
    table = "PALESYA_LEADS"
    old_table = "PALESYA_LEADS_PRIVACY_V13_OLD"
    columns = list(connection.execute('PRAGMA table_info("{}")'.format(table)))
    original_sql = connection.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone()[0]
    indexes = [
        row[0] for row in connection.execute(
            "SELECT sql FROM sqlite_master "
            "WHERE type='index' AND tbl_name=? AND sql IS NOT NULL", (table,)
        )
    ]
    definitions = []
    for _, name, column_type, not_null, default, primary_key in columns:
        definition = [_quote_sqlite_identifier(name)]
        if column_type:
            definition.append(column_type)
        if str(name).upper() != "PRIVACY_NOTICE_VERSION":
            if not_null:
                definition.append("NOT NULL")
            if default is not None:
                definition.extend(("DEFAULT", default))
        if primary_key:
            definition.append("PRIMARY KEY")
            if str(column_type).upper() == "INTEGER" and "AUTOINCREMENT" in original_sql.upper():
                definition.append("AUTOINCREMENT")
        definitions.append(" ".join(definition))
    quoted_columns = ",".join(_quote_sqlite_identifier(row[1]) for row in columns)
    connection.execute(
        'ALTER TABLE "{}" RENAME TO "{}"'.format(table, old_table)
    )
    connection.execute(
        'CREATE TABLE "{}"({})'.format(table, ",".join(definitions))
    )
    connection.execute(
        'INSERT INTO "{table}"({columns}) SELECT {columns} FROM "{old}"'.format(
            table=table, columns=quoted_columns, old=old_table,
        )
    )
    connection.execute('DROP TABLE "{}"'.format(old_table))
    for statement in indexes:
        connection.execute(statement)


def _price_value(value):
    """Normalizza importi numerici e stringhe italiane senza inventare prezzi."""
    if value is None or isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        price = float(value)
    else:
        raw = str(value).strip().replace("€", "").replace(" ", "")
        if not raw:
            return None
        if "," in raw and "." in raw:
            if raw.rfind(",") > raw.rfind("."):
                raw = raw.replace(".", "").replace(",", ".")
            else:
                raw = raw.replace(",", "")
        else:
            raw = raw.replace(",", ".")
        try:
            price = float(raw)
        except (TypeError, ValueError):
            return None
    if price <= 0 or price > 10_000_000:
        return None
    return round(price, 2)


def _candidate_price_columns(columns, target, preferred):
    """Trova campi prezzo legacy noti e, in coda, varianti equivalenti."""
    target = target.upper()
    ordered = []
    for name in preferred:
        actual = columns.get(name.upper())
        if actual and name.upper() != target and actual not in ordered:
            ordered.append(actual)
    for upper, actual in columns.items():
        if upper == target or upper in {"IVA", "ALIQUOTA_IVA"}:
            continue
        if any(hint in upper for hint in ("PREZZ", "COST", "IMPORT", "TARIFF", "QUOTA")):
            if actual not in ordered:
                ordered.append(actual)
    return ordered


def _backfill_direct_prices(connection, table, target, candidates):
    if not candidates:
        return 0
    quoted = ",".join('"{}"'.format(name.replace('"', '""')) for name in candidates)
    rows = connection.execute(
        'SELECT rowid,"{}",{} FROM "{}"'.format(target, quoted, table)
    ).fetchall()
    recovered = 0
    for row in rows:
        if _price_value(row[1]) is not None:
            continue
        price = next((_price_value(value) for value in row[2:] if _price_value(value) is not None), None)
        if price is None:
            continue
        connection.execute(
            'UPDATE "{}" SET "{}"=? WHERE rowid=?'.format(table, target),
            (price, row[0]),
        )
        recovered += 1
    return recovered


def _historical_subscription_prices(connection, foreign_key):
    """Prezzo piu recente per listino/attivita, privilegiando il totale tessera."""
    tables = {
        str(row[0]).upper() for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        )
    }
    if "TESSERE" not in tables:
        return {}
    columns = _table_columns(connection, "TESSERE")
    key = columns.get(foreign_key.upper())
    if not key:
        return {}
    amounts = [
        columns[name] for name in ("IMP_TOT", "IMPORTO", "PREZZO", "COSTO", "TARIFFA")
        if name in columns
    ]
    if not amounts:
        return {}
    markers = [
        columns[name] for name in ("DATA_AGG", "DATA_REG", "DATA_NEW", "DATA_FIN", "ID")
        if name in columns
    ]
    selected = [key] + amounts + markers
    quoted = ",".join('"{}"'.format(name.replace('"', '""')) for name in selected)
    recovered = {}
    for row in connection.execute('SELECT rowid,{} FROM TESSERE'.format(quoted)):
        entity_id = row[1]
        if entity_id is None:
            continue
        price = next(
            (_price_value(value) for value in row[2:2 + len(amounts)] if _price_value(value) is not None),
            None,
        )
        if price is None:
            continue
        marker_values = row[2 + len(amounts):]
        marker = tuple(str(value or "") for value in marker_values) + (int(row[0]),)
        previous = recovered.get(entity_id)
        if previous is None or marker >= previous[0]:
            recovered[entity_id] = (marker, price)
    return {entity_id: value[1] for entity_id, value in recovered.items()}


def _backfill_historical_prices(connection, table, target, foreign_key):
    columns = _table_columns(connection, table)
    identifier = columns.get("ID")
    if not identifier:
        return 0
    historical = _historical_subscription_prices(connection, foreign_key)
    recovered = 0
    for entity_id, price in historical.items():
        row = connection.execute(
            'SELECT "{}" FROM "{}" WHERE "{}"=?'.format(target, table, identifier),
            (entity_id,),
        ).fetchone()
        if row is None or _price_value(row[0]) is not None:
            continue
        connection.execute(
            'UPDATE "{}" SET "{}"=? WHERE "{}"=?'.format(table, target, identifier),
            (price, entity_id),
        )
        recovered += 1
    return recovered


def recover_legacy_prices(connection):
    """Recupera prezzi ForFit senza sovrascrivere valori gia configurati.

    Prima usa eventuali colonne prezzo native della tabella legacy; se non sono
    valorizzate usa il totale dell'abbonamento piu recente collegato allo stesso
    listino o alla stessa attivita.
    """
    result = {"listini": 0, "attivita": 0}
    listino_columns = _table_columns(connection, "LISTINI")
    result["listini"] += _backfill_direct_prices(
        connection, "LISTINI", "PREZZO",
        _candidate_price_columns(
            listino_columns, "PREZZO",
            ("IMPORTO", "COSTO", "COSTO_UN", "TARIFFA", "QUOTA", "IMP_TOT"),
        ),
    )
    result["listini"] += _backfill_historical_prices(
        connection, "LISTINI", "PREZZO", "COD_LIS"
    )
    attivita_columns = _table_columns(connection, "ATTIVITA")
    result["attivita"] += _backfill_direct_prices(
        connection, "ATTIVITA", "COSTO_UN",
        _candidate_price_columns(
            attivita_columns, "COSTO_UN",
            ("PREZZO", "IMPORTO", "COSTO", "TARIFFA", "QUOTA", "IMP_TOT"),
        ),
    )
    result["attivita"] += _backfill_historical_prices(
        connection, "ATTIVITA", "COSTO_UN", "COD_ATT"
    )
    return result


def ensure_schema(path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(str(path), timeout=30)
    try:
        con.execute("PRAGMA foreign_keys=ON")
        con.execute("PRAGMA journal_mode=WAL")
        con.execute("PRAGMA busy_timeout=10000")
        con.executescript(DDL)
        _rebuild_receipts_without_legacy_cash_foreign_key(con)
        socio_columns = {row[1].upper() for row in con.execute("PRAGMA table_info(SOCI)")}
        if "BIO" not in socio_columns:
            con.execute("ALTER TABLE SOCI ADD COLUMN BIO TEXT")
        for name in (
            "COGNOME", "NOME", "FEDERATION_NAME", "FEDERATION_CARD",
            "FEDERATION_EXPIRY", "GUARDIAN_NAME", "GUARDIAN_TAX_CODE",
            "GUARDIAN_RELATIONSHIP", "GUARDIAN_EMAIL", "GUARDIAN_PHONE",
        ):
            if name not in socio_columns:
                con.execute('ALTER TABLE SOCI ADD COLUMN "{}" TEXT'.format(name))
        listino_columns = _table_columns(con, "LISTINI")
        for name, declaration in {
            "GIORNI": "INTEGER DEFAULT 0",
            "DURATA": "INTEGER DEFAULT 0",
            "PREZZO": "REAL DEFAULT 0",
            "ACTIVITY_ID": "INTEGER",
            "FREQUENCY_LABEL": "TEXT",
            "PRICING_MODE": "TEXT NOT NULL DEFAULT 'FIXED'",
            "ACTIVE": "INTEGER NOT NULL DEFAULT 1",
        }.items():
            if name not in listino_columns:
                con.execute('ALTER TABLE LISTINI ADD COLUMN "{}" {}'.format(name, declaration))
        attivita_columns = _table_columns(con, "ATTIVITA")
        for name, declaration in {
            "COSTO_UN": "REAL DEFAULT 0",
            "IVA": "REAL DEFAULT 0",
            "ACTIVE": "INTEGER NOT NULL DEFAULT 1",
            "PALESYA_KIND": "TEXT",
            "PALESYA_SECTOR": "TEXT",
            "PALESYA_SUBSECTOR": "TEXT",
            "PALESYA_TAXONOMY_SOURCE": "TEXT",
            "PALESYA_TAXONOMY_CONFIDENCE": "INTEGER NOT NULL DEFAULT 0",
        }.items():
            if name not in attivita_columns:
                con.execute('ALTER TABLE ATTIVITA ADD COLUMN "{}" {}'.format(name, declaration))
        # Le varianti ForFit conservano la divisione del catalogo in colonne
        # diverse. La ricostruiamo solo sulle righe non ancora classificate:
        # aggiornamenti successivi non sovrascrivono le scelte della palestra.
        missing_taxonomy = con.execute(
            """SELECT COUNT(*) FROM ATTIVITA
               WHERE PALESYA_SECTOR IS NULL OR TRIM(PALESYA_SECTOR)=''"""
        ).fetchone()[0]
        if missing_taxonomy:
            import forfit_catalog
            forfit_catalog.import_into(con, overwrite=False)
        recover_legacy_prices(con)
        istruttori_columns = _table_columns(con, "ISTRU")
        if "ACTIVE" not in istruttori_columns:
            con.execute('ALTER TABLE ISTRU ADD COLUMN "ACTIVE" INTEGER NOT NULL DEFAULT 1')
        payment_method_columns = _table_columns(con, "MODPAG")
        if "ACTIVE" not in payment_method_columns:
            con.execute('ALTER TABLE MODPAG ADD COLUMN "ACTIVE" INTEGER NOT NULL DEFAULT 1')
        subscription_columns = _table_columns(con, "TESSERE")
        for name, declaration in {
            "SCONTO_PCT": "REAL DEFAULT 0",
            "LESSON_COUNT": "INTEGER",
            "UNIT_PRICE": "REAL",
            "MAX_WEEKLY_ENTRIES": "INTEGER DEFAULT 0",
            "MAX_MONTHLY_ENTRIES": "INTEGER DEFAULT 0",
        }.items():
            if name not in subscription_columns:
                con.execute('ALTER TABLE TESSERE ADD COLUMN "{}" {}'.format(name, declaration))
        subscription_columns = _table_columns(con, "TESSERE")
        if {"COD_SOC", "DATA_VAL", "DATA_FIN", "STATO"}.issubset(subscription_columns):
            con.execute(
                """CREATE INDEX IF NOT EXISTS IX_TESSERE_SOCIO_VALIDITA
                   ON TESSERE(COD_SOC,DATA_VAL,DATA_FIN,STATO)"""
            )
        business_columns = _table_columns(con, "GYMFLOW_BUSINESS_PROFILE")
        for name, declaration in {
            "FACILITY_TYPE": "TEXT NOT NULL DEFAULT 'MULTISPORT'",
            "REGISTRATION_TERMS_GYM": "TEXT",
            "REGISTRATION_TERMS_POOL": "TEXT",
        }.items():
            if name not in business_columns:
                con.execute(
                    'ALTER TABLE GYMFLOW_BUSINESS_PROFILE ADD COLUMN "{}" {}'.format(
                        name, declaration
                    )
                )
        user_columns = _table_columns(con, "GYMFLOW_USERS")
        if "DISPLAY_NAME" not in user_columns:
            con.execute('ALTER TABLE GYMFLOW_USERS ADD COLUMN "DISPLAY_NAME" TEXT')
        scadenze_columns = {row[1].upper() for row in con.execute("PRAGMA table_info(SCADENZ)")}
        if "ID_TESSERA" not in scadenze_columns:
            con.execute("ALTER TABLE SCADENZ ADD COLUMN ID_TESSERA INTEGER")
        site_columns = {row[1].upper() for row in con.execute("PRAGMA table_info(GYMFLOW_FLEET_SITES)")}
        site_owner_added = "BILLING_OWNER" not in site_columns
        if site_owner_added:
            con.execute("ALTER TABLE GYMFLOW_FLEET_SITES ADD COLUMN BILLING_OWNER TEXT NOT NULL DEFAULT 'CIRO'")
        license_columns = {row[1].upper() for row in con.execute("PRAGMA table_info(GYMFLOW_LICENSES)")}
        license_owner_added = "BILLING_OWNER" not in license_columns
        for name, declaration in {
            "MONTHLY_PRICE_CENTS": "INTEGER NOT NULL DEFAULT 0",
            "SETUP_PRICE_CENTS": "INTEGER NOT NULL DEFAULT 0",
            "CURRENCY": "TEXT NOT NULL DEFAULT 'EUR'",
            "BILLING_PROVIDER": "TEXT NOT NULL DEFAULT 'PAYPAL'",
            "BILLING_INTERVAL": "TEXT NOT NULL DEFAULT 'MONTH'",
            "BILLING_OWNER": "TEXT NOT NULL DEFAULT 'CIRO'",
            "CONFIG_PROFILE_ID": "TEXT",
        }.items():
            if name not in license_columns:
                con.execute('ALTER TABLE GYMFLOW_LICENSES ADD COLUMN "{}" {}'.format(name, declaration))
        billing_columns = {row[1].upper() for row in con.execute("PRAGMA table_info(GYMFLOW_BILLING_EVENTS)")}
        for name, declaration in {
            "SITE_ID": "INTEGER",
            "AMOUNT_CENTS": "INTEGER NOT NULL DEFAULT 0",
            "CURRENCY": "TEXT NOT NULL DEFAULT 'EUR'",
            "PAYMENT_STATUS": "TEXT",
            "BILLING_OWNER": "TEXT NOT NULL DEFAULT 'CIRO'",
        }.items():
            if name not in billing_columns:
                con.execute('ALTER TABLE GYMFLOW_BILLING_EVENTS ADD COLUMN "{}" {}'.format(name, declaration))
        privacy_v13_applied = con.execute(
            "SELECT 1 FROM GYMFLOW_SCHEMA_VERSION WHERE VERSION=13"
        ).fetchone() is not None
        lead_columns = {row[1].upper() for row in con.execute("PRAGMA table_info(PALESYA_LEADS)")}
        for name, declaration in {
            "PRIVACY_NOTICE_VERSION": "TEXT",
            "PRIVACY_ACK_AT": "TEXT",
            "MARKETING_CONSENT_AT": "TEXT",
        }.items():
            if name not in lead_columns:
                con.execute('ALTER TABLE PALESYA_LEADS ADD COLUMN "{}" {}'.format(name, declaration))
        privacy_column = next(
            row for row in con.execute("PRAGMA table_info(PALESYA_LEADS)")
            if row[1].upper() == "PRIVACY_NOTICE_VERSION"
        )
        if privacy_column[3] or privacy_column[4] is not None:
            _rebuild_leads_with_nullable_privacy_version(con)
        if not privacy_v13_applied:
            con.execute(
                """UPDATE PALESYA_LEADS
                   SET PRIVACY_NOTICE_VERSION=NULL, PRIVACY_ACK_AT=NULL
                   WHERE PRIVACY_NOTICE_VERSION=?
                     AND PRIVACY_ACK_AT=CONSENT_AT
                     AND CREATED_AT < ?""",
                (PRIVACY_NOTICE_VERSION, PRIVACY_HISTORY_CUTOFF),
            )
        license_owner_filter = "1=1" if license_owner_added else "BILLING_OWNER IS NULL OR TRIM(BILLING_OWNER)=''"
        con.execute(
            """UPDATE GYMFLOW_LICENSES
               SET BILLING_OWNER=CASE WHEN BILLING_PROVIDER='STRIPE' THEN 'LORENZO' ELSE 'CIRO' END
               WHERE {}""".format(license_owner_filter)
        )
        site_owner_filter = "1=1" if site_owner_added else "BILLING_OWNER IS NULL OR TRIM(BILLING_OWNER)=''"
        con.execute(
            """UPDATE GYMFLOW_FLEET_SITES
               SET BILLING_OWNER=COALESCE((
                   SELECT l.BILLING_OWNER FROM GYMFLOW_LICENSES l
                   WHERE l.SITE_ID=GYMFLOW_FLEET_SITES.ID
               ),'CIRO')
               WHERE {}""".format(site_owner_filter)
        )
        con.execute(
            """UPDATE GYMFLOW_ORGANIZATIONS
               SET BILLING_OWNER=COALESCE((
                   SELECT s.BILLING_OWNER FROM GYMFLOW_FLEET_SITES s
                   WHERE s.ORGANIZATION_ID=GYMFLOW_ORGANIZATIONS.ID
                   ORDER BY s.ID LIMIT 1
               ),'CIRO')
               WHERE BILLING_OWNER IS NULL OR TRIM(BILLING_OWNER) NOT IN ('CIRO','LORENZO')"""
        )
        installation_columns = {row[1].upper() for row in con.execute("PRAGMA table_info(GYMFLOW_INSTALLATIONS)")}
        for name, declaration in {
            "CONFIG_PROFILE_ID": "TEXT",
            "CONFIG_PROFILE_HASH": "TEXT",
            "CONFIG_STATUS": "TEXT",
            "CONFIG_ERROR": "TEXT",
            "UPDATE_STATUS": "TEXT",
            "UPDATE_VERSION": "TEXT",
            "UPDATE_CHECKED_AT": "TEXT",
            "UPDATE_ERROR": "TEXT",
            "DIAGNOSTICS_JSON": "TEXT",
            "DIAGNOSTICS_AT": "TEXT",
            "UPDATE_INSTALL_ON_EXIT": "INTEGER NOT NULL DEFAULT 0",
            "RECOVERY_TOKEN_HASH": "TEXT",
        }.items():
            if name not in installation_columns:
                con.execute('ALTER TABLE GYMFLOW_INSTALLATIONS ADD COLUMN "{}" {}'.format(name, declaration))
        profile_columns = {row[1].upper() for row in con.execute("PRAGMA table_info(GYMFLOW_CONFIGURATION_PROFILES)")}
        if "SITE_ID" not in profile_columns:
            con.execute('ALTER TABLE GYMFLOW_CONFIGURATION_PROFILES ADD COLUMN "SITE_ID" INTEGER')
        con.execute(
            """UPDATE GYMFLOW_CONFIGURATION_PROFILES
               SET SITE_ID=(SELECT MIN(l.SITE_ID) FROM GYMFLOW_LICENSES l
                            WHERE l.CONFIG_PROFILE_ID=GYMFLOW_CONFIGURATION_PROFILES.ID)
               WHERE SITE_ID IS NULL AND 1=(
                   SELECT COUNT(DISTINCT l.SITE_ID) FROM GYMFLOW_LICENSES l
                   WHERE l.CONFIG_PROFILE_ID=GYMFLOW_CONFIGURATION_PROFILES.ID
               )"""
        )
        user_columns = {row[1].upper() for row in con.execute("PRAGMA table_info(GYMFLOW_USERS)")}
        for name, declaration in {
            "TOTP_SECRET": "TEXT",
            "TOTP_ENABLED": "INTEGER NOT NULL DEFAULT 0",
            "FAILED_LOGIN_COUNT": "INTEGER NOT NULL DEFAULT 0",
            "LOCKED_UNTIL": "TEXT",
        }.items():
            if name not in user_columns:
                con.execute('ALTER TABLE GYMFLOW_USERS ADD COLUMN "{}" {}'.format(name, declaration))
        session_columns = {row[1].upper() for row in con.execute("PRAGMA table_info(GYMFLOW_SESSIONS)")}
        if "MFA_VERIFIED" not in session_columns:
            con.execute('ALTER TABLE GYMFLOW_SESSIONS ADD COLUMN "MFA_VERIFIED" INTEGER NOT NULL DEFAULT 1')
        slot_columns = {row[1].upper() for row in con.execute("PRAGMA table_info(GYMFLOW_SCHEDULE_SLOTS)")}
        for name, declaration in {
            "CAPACITY_LIMIT": "INTEGER",
            "UNLIMITED_CAPACITY": "INTEGER NOT NULL DEFAULT 0",
        }.items():
            if name not in slot_columns:
                con.execute('ALTER TABLE GYMFLOW_SCHEDULE_SLOTS ADD COLUMN "{}" {}'.format(name, declaration))
        enrollment_columns = _table_columns(con, "GYMFLOW_SLOT_ENROLLMENTS")
        for name, declaration in {
            "LANE_NUMBER": "INTEGER",
            "BOOKING_KIND": "TEXT NOT NULL DEFAULT 'STANDARD'",
            "PAYMENT_REQUIRED": "INTEGER NOT NULL DEFAULT 1",
            "NOTE": "TEXT",
        }.items():
            if name not in enrollment_columns:
                con.execute(
                    'ALTER TABLE GYMFLOW_SLOT_ENROLLMENTS ADD COLUMN "{}" {}'.format(
                        name, declaration
                    )
                )
        receipt_columns = _table_columns(con, "GYMFLOW_RECEIPTS")
        for name, declaration in {
            "STATUS": "TEXT NOT NULL DEFAULT 'ISSUED'",
            "VOIDED_AT": "TEXT",
            "VOID_REASON": "TEXT",
            "VOIDED_BY": "INTEGER",
        }.items():
            if name not in receipt_columns:
                con.execute(
                    'ALTER TABLE GYMFLOW_RECEIPTS ADD COLUMN "{}" {}'.format(
                        name, declaration
                    )
                )
        # Gli estratti ForFit possono avere versioni ridotte delle tabelle core.
        # Gli indici prestazionali vanno quindi creati solo quando tutte le
        # colonne richieste sono realmente presenti, senza bloccare la migrazione.
        for index_name, table, columns in (
            ("IX_TESSERE_VALIDITA", "TESSERE", ("DATA_VAL", "DATA_FIN", "STATO")),
            ("IX_TESSERE_SCADENZA", "TESSERE", ("DATA_FIN", "STATO", "COD_SOC")),
            ("IX_TESSERE_ATTIVITA_VALIDITA", "TESSERE", ("COD_ATT", "DATA_VAL", "DATA_FIN", "STATO", "COD_SOC")),
            ("IX_RINGRES_DATA", "RINGRES", ("DATA_IN",)),
            ("IX_RINGRES_DATA_SOCIO", "RINGRES", ("DATA_IN", "COD_SOC")),
            ("IX_SOCI_DATA_ISCRIZIONE", "SOCI", ("DATA_IS",)),
            ("IX_SOCI_CERTIFICATO_SCADENZA", "SOCI", ("DT_SC_CM",)),
            ("IX_CASSA_DATA_TIPO", "CASSA", ("DATA", "T_OP")),
        ):
            available = _table_columns(con, table)
            if set(columns).issubset(available):
                con.execute('CREATE INDEX IF NOT EXISTS "{}" ON "{}" ({})'.format(
                    index_name, table, ",".join('"{}"'.format(column) for column in columns)
                ))
        receipts_v18_applied = con.execute(
            "SELECT 1 FROM GYMFLOW_SCHEMA_VERSION WHERE VERSION=18"
        ).fetchone() is not None
        cash_columns = _table_columns(con, "CASSA")
        # Una migrazione precedente puo avere gia numerato alcune ricevute prima
        # di incontrare il FK legacy. Riallineare i contatori evita di riusare
        # lo stesso numero quando l'avvio riprende.
        for receipt_year, last_sequence in con.execute(
            """SELECT RECEIPT_YEAR,MAX(RECEIPT_SEQUENCE)
               FROM GYMFLOW_RECEIPTS GROUP BY RECEIPT_YEAR"""
        ):
            con.execute(
                "INSERT OR IGNORE INTO GYMFLOW_RECEIPT_COUNTERS(YEAR,LAST_NUMBER) VALUES(?,0)",
                (receipt_year,),
            )
            con.execute(
                """UPDATE GYMFLOW_RECEIPT_COUNTERS
                   SET LAST_NUMBER=MAX(LAST_NUMBER,?) WHERE YEAR=?""",
                (last_sequence, receipt_year),
            )
        if not receipts_v18_applied and {"ID", "DATA", "COD_SOCIO", "IMPORTO"}.issubset(cash_columns):
            operation_filter = "AND UPPER(COALESCE(T_OP,'E'))<>'U'" if "T_OP" in cash_columns else ""
            for payment_id, payment_date in con.execute(
                """SELECT ID,substr(MIN(DATA),1,10) FROM CASSA
                   WHERE COD_SOCIO IS NOT NULL AND COALESCE(IMPORTO,0)>0 {}
                     AND ID NOT IN (SELECT PAYMENT_ID FROM GYMFLOW_RECEIPTS)
                   GROUP BY ID
                   ORDER BY substr(DATA,1,10),ID""".format(operation_filter)
            ):
                try:
                    year = int(str(payment_date or "")[:4])
                    if year < 1900 or year > 9999:
                        raise ValueError
                except (TypeError, ValueError):
                    import datetime as _datetime
                    year = _datetime.date.today().year
                con.execute(
                    "INSERT OR IGNORE INTO GYMFLOW_RECEIPT_COUNTERS(YEAR,LAST_NUMBER) VALUES(?,0)",
                    (year,),
                )
                con.execute(
                    "UPDATE GYMFLOW_RECEIPT_COUNTERS SET LAST_NUMBER=LAST_NUMBER+1 WHERE YEAR=?",
                    (year,),
                )
                sequence = con.execute(
                    "SELECT LAST_NUMBER FROM GYMFLOW_RECEIPT_COUNTERS WHERE YEAR=?", (year,)
                ).fetchone()[0]
                con.execute(
                    """INSERT INTO GYMFLOW_RECEIPTS
                       (PAYMENT_ID,RECEIPT_YEAR,RECEIPT_SEQUENCE,RECEIPT_NUMBER)
                       VALUES(?,?,?,?)""",
                    (payment_id, year, sequence, "{}/{:06d}".format(year, sequence)),
                )
        con.execute("INSERT OR IGNORE INTO GYMFLOW_SCHEMA_VERSION(VERSION) VALUES(?)", (SCHEMA_VERSION,))
        con.commit()
    finally:
        con.close()
