"""Schema SQLite minimo del centralino AI.

Contiene SOLO le tabelle tecniche dell'assistenza telefonica (idempotenza,
sessioni, ledger, audit, callback, log chiamata, richieste commerciali). Non
include la struttura del gestionale Palesya: questo servizio è isolato.
"""
from pathlib import Path

import db_compat


SUPPORT_SCHEMA = """
CREATE TABLE IF NOT EXISTS SUPPORT_WEBHOOK_EVENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SOURCE TEXT NOT NULL,
    EVENT_ID TEXT NOT NULL,
    EVENT_TYPE TEXT,
    CALL_ID TEXT,
    OCCURRED_AT TEXT,
    PAYLOAD_HASH TEXT,
    STATUS TEXT NOT NULL DEFAULT 'RECEIVED',
    ERROR TEXT,
    RECEIVED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROCESSED_AT TEXT,
    UNIQUE(SOURCE, EVENT_ID)
);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_WEBHOOK_CALL ON SUPPORT_WEBHOOK_EVENTS(CALL_ID, RECEIVED_AT);

CREATE TABLE IF NOT EXISTS SUPPORT_CALL_SESSIONS(
    CALL_ID TEXT PRIMARY KEY,
    TELNYX_CALL_ID TEXT,
    VOICE_AI_CALL_ID TEXT,
    FROM_PHONE TEXT,
    TO_PHONE TEXT,
    CUSTOMER_MATCH_STATUS TEXT NOT NULL DEFAULT 'unknown',
    CONTACT_ID TEXT,
    COMPANY_ID TEXT,
    COMPANY_NAME TEXT,
    CONTEXT_JSON TEXT,
    TICKET_ID TEXT,
    STATE TEXT NOT NULL DEFAULT 'started',
    STARTED_AT TEXT,
    ANSWERED_AT TEXT,
    ENDED_AT TEXT,
    DURATION_SECONDS INTEGER,
    SUMMARY_JSON TEXT,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_SESSION_COMPANY ON SUPPORT_CALL_SESSIONS(COMPANY_ID, UPDATED_AT);

CREATE TABLE IF NOT EXISTS SUPPORT_TICKET_LINKS(
    CALL_ID TEXT PRIMARY KEY,
    HUBSPOT_TICKET_ID TEXT NOT NULL UNIQUE,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SUPPORT_CONSUMPTION_LEDGER(
    CALL_ID TEXT PRIMARY KEY,
    EVENT_ID TEXT NOT NULL,
    COMPANY_ID TEXT NOT NULL,
    HUBSPOT_TICKET_ID TEXT,
    BEFORE_COUNT INTEGER NOT NULL,
    AFTER_COUNT INTEGER NOT NULL,
    CONSUMED INTEGER NOT NULL DEFAULT 1,
    STATUS TEXT NOT NULL DEFAULT 'APPLIED',
    REASON TEXT,
    REVERSED_AT TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_LEDGER_COMPANY ON SUPPORT_CONSUMPTION_LEDGER(COMPANY_ID, CREATED_AT);

CREATE TABLE IF NOT EXISTS SUPPORT_AUDIT_LOG(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EVENT_KEY TEXT NOT NULL UNIQUE,
    CALL_ID TEXT,
    COMPANY_ID TEXT,
    HUBSPOT_TICKET_ID TEXT,
    BEFORE_COUNT INTEGER,
    CONSUMED INTEGER NOT NULL DEFAULT 0,
    AFTER_COUNT INTEGER,
    REASON TEXT,
    SOURCE TEXT,
    TELNYX_CALL_ID TEXT,
    VOICE_AI_CALL_ID TEXT,
    ACTOR TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_AUDIT_COMPANY ON SUPPORT_AUDIT_LOG(COMPANY_ID, CREATED_AT);

CREATE TABLE IF NOT EXISTS SUPPORT_CALLBACKS(
    CALL_ID TEXT PRIMARY KEY,
    COMPANY_ID TEXT,
    CONTACT_ID TEXT,
    CALLER_PHONE TEXT,
    CALLER_NAME TEXT,
    COMPANY_NAME TEXT,
    REASON TEXT,
    CATEGORY TEXT,
    HUBSPOT_TASK_ID TEXT,
    STATUS TEXT NOT NULL DEFAULT 'OPEN',
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_CALLBACK_COMPANY ON SUPPORT_CALLBACKS(COMPANY_ID, CREATED_AT);

CREATE TABLE IF NOT EXISTS SUPPORT_CALL_LOG(
    CALL_ID TEXT PRIMARY KEY,
    HUBSPOT_CALL_ID TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SUPPORT_COMMERCIAL_LINKS(
    CALL_ID TEXT PRIMARY KEY,
    HUBSPOT_DEAL_ID TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Memoria di smistamento. Ogni classificazione viene registrata con la sua
-- previsione. Quando un umano corregge la categoria o la gravita, la riga
-- viene confermata. Il modello impara SOLO dalle righe confermate.
CREATE TABLE IF NOT EXISTS SUPPORT_TRIAGE_EVENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CALL_ID TEXT,
    TICKET_ID TEXT,
    COMPANY_ID TEXT,
    REQUEST_TEXT TEXT NOT NULL,
    PREDICTED_CATEGORY TEXT,
    PREDICTED_SEVERITY TEXT,
    PREDICTED_CONFIDENCE REAL,
    PREDICTION_SOURCE TEXT,
    CONFIRMED_CATEGORY TEXT,
    CONFIRMED_SEVERITY TEXT,
    CONFIRMED_BY TEXT,
    CONFIRMED_AT TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_TRIAGE_CONFIRMED ON SUPPORT_TRIAGE_EVENTS(CONFIRMED_AT);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_TRIAGE_COMPANY ON SUPPORT_TRIAGE_EVENTS(COMPANY_ID, CREATED_AT);
CREATE INDEX IF NOT EXISTS IX_SUPPORT_TRIAGE_CALL ON SUPPORT_TRIAGE_EVENTS(CALL_ID);
"""


def ensure_schema(target):
    """Crea (idempotente) le sole tabelle tecniche del centralino.

    Funziona sia su SQLite (percorso file) sia su Postgres (DATABASE_URL).
    """
    if db_compat.is_postgres(target):
        ddl = SUPPORT_SCHEMA.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "SERIAL PRIMARY KEY")
        con = db_compat.connect(target)
        try:
            con.executescript(ddl)
        finally:
            con.close()
        return str(target)
    path = Path(target)
    path.parent.mkdir(parents=True, exist_ok=True)
    con = db_compat.connect(str(path))
    try:
        con.executescript(SUPPORT_SCHEMA)
        con.commit()
    finally:
        con.close()
    return str(path)
